//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace SisATU.Servicios.ServiceATU {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Servicio_ATUSoap", Namespace="http://tempuri.org/")]
    public partial class Servicio_ATU : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ConsultaDNIOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultaLicenciaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultaPlacaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsulMigraOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultaPTPOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultaRUCOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultaTokenOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultaCITVOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultaSOATOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultaPapeletaOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Servicio_ATU() {
            this.Url = global::SisATU.Servicios.Properties.Settings.Default.SisATU_Servicios_ServiceATU_Servicio_ATU;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ConsultaDNICompletedEventHandler ConsultaDNICompleted;
        
        /// <remarks/>
        public event ConsultaLicenciaCompletedEventHandler ConsultaLicenciaCompleted;
        
        /// <remarks/>
        public event ConsultaPlacaCompletedEventHandler ConsultaPlacaCompleted;
        
        /// <remarks/>
        public event ConsulMigraCompletedEventHandler ConsulMigraCompleted;
        
        /// <remarks/>
        public event ConsultaPTPCompletedEventHandler ConsultaPTPCompleted;
        
        /// <remarks/>
        public event ConsultaRUCCompletedEventHandler ConsultaRUCCompleted;
        
        /// <remarks/>
        public event ConsultaTokenCompletedEventHandler ConsultaTokenCompleted;
        
        /// <remarks/>
        public event ConsultaCITVCompletedEventHandler ConsultaCITVCompleted;
        
        /// <remarks/>
        public event ConsultaSOATCompletedEventHandler ConsultaSOATCompleted;
        
        /// <remarks/>
        public event ConsultaPapeletaCompletedEventHandler ConsultaPapeletaCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConsultaDNI", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Persona ConsultaDNI(Usuario user, string DNI) {
            object[] results = this.Invoke("ConsultaDNI", new object[] {
                        user,
                        DNI});
            return ((Persona)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaDNIAsync(Usuario user, string DNI) {
            this.ConsultaDNIAsync(user, DNI, null);
        }
        
        /// <remarks/>
        public void ConsultaDNIAsync(Usuario user, string DNI, object userState) {
            if ((this.ConsultaDNIOperationCompleted == null)) {
                this.ConsultaDNIOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaDNIOperationCompleted);
            }
            this.InvokeAsync("ConsultaDNI", new object[] {
                        user,
                        DNI}, this.ConsultaDNIOperationCompleted, userState);
        }
        
        private void OnConsultaDNIOperationCompleted(object arg) {
            if ((this.ConsultaDNICompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaDNICompleted(this, new ConsultaDNICompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConsultaLicencia", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Conductor ConsultaLicencia(Usuario user, string DNI, string TIPDOC) {
            object[] results = this.Invoke("ConsultaLicencia", new object[] {
                        user,
                        DNI,
                        TIPDOC});
            return ((Conductor)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaLicenciaAsync(Usuario user, string DNI, string TIPDOC) {
            this.ConsultaLicenciaAsync(user, DNI, TIPDOC, null);
        }
        
        /// <remarks/>
        public void ConsultaLicenciaAsync(Usuario user, string DNI, string TIPDOC, object userState) {
            if ((this.ConsultaLicenciaOperationCompleted == null)) {
                this.ConsultaLicenciaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaLicenciaOperationCompleted);
            }
            this.InvokeAsync("ConsultaLicencia", new object[] {
                        user,
                        DNI,
                        TIPDOC}, this.ConsultaLicenciaOperationCompleted, userState);
        }
        
        private void OnConsultaLicenciaOperationCompleted(object arg) {
            if ((this.ConsultaLicenciaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaLicenciaCompleted(this, new ConsultaLicenciaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConsultaPlaca", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Vehiculo ConsultaPlaca(Usuario user, string PLACA) {
            object[] results = this.Invoke("ConsultaPlaca", new object[] {
                        user,
                        PLACA});
            return ((Vehiculo)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaPlacaAsync(Usuario user, string PLACA) {
            this.ConsultaPlacaAsync(user, PLACA, null);
        }
        
        /// <remarks/>
        public void ConsultaPlacaAsync(Usuario user, string PLACA, object userState) {
            if ((this.ConsultaPlacaOperationCompleted == null)) {
                this.ConsultaPlacaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaPlacaOperationCompleted);
            }
            this.InvokeAsync("ConsultaPlaca", new object[] {
                        user,
                        PLACA}, this.ConsultaPlacaOperationCompleted, userState);
        }
        
        private void OnConsultaPlacaOperationCompleted(object arg) {
            if ((this.ConsultaPlacaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaPlacaCompleted(this, new ConsultaPlacaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConsulMigra", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Migraciones ConsulMigra(Usuario user, string CE) {
            object[] results = this.Invoke("ConsulMigra", new object[] {
                        user,
                        CE});
            return ((Migraciones)(results[0]));
        }
        
        /// <remarks/>
        public void ConsulMigraAsync(Usuario user, string CE) {
            this.ConsulMigraAsync(user, CE, null);
        }
        
        /// <remarks/>
        public void ConsulMigraAsync(Usuario user, string CE, object userState) {
            if ((this.ConsulMigraOperationCompleted == null)) {
                this.ConsulMigraOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsulMigraOperationCompleted);
            }
            this.InvokeAsync("ConsulMigra", new object[] {
                        user,
                        CE}, this.ConsulMigraOperationCompleted, userState);
        }
        
        private void OnConsulMigraOperationCompleted(object arg) {
            if ((this.ConsulMigraCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsulMigraCompleted(this, new ConsulMigraCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConsultaPTP", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PermiTempPerm ConsultaPTP(Usuario user, string PTP, string TIPDOC) {
            object[] results = this.Invoke("ConsultaPTP", new object[] {
                        user,
                        PTP,
                        TIPDOC});
            return ((PermiTempPerm)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaPTPAsync(Usuario user, string PTP, string TIPDOC) {
            this.ConsultaPTPAsync(user, PTP, TIPDOC, null);
        }
        
        /// <remarks/>
        public void ConsultaPTPAsync(Usuario user, string PTP, string TIPDOC, object userState) {
            if ((this.ConsultaPTPOperationCompleted == null)) {
                this.ConsultaPTPOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaPTPOperationCompleted);
            }
            this.InvokeAsync("ConsultaPTP", new object[] {
                        user,
                        PTP,
                        TIPDOC}, this.ConsultaPTPOperationCompleted, userState);
        }
        
        private void OnConsultaPTPOperationCompleted(object arg) {
            if ((this.ConsultaPTPCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaPTPCompleted(this, new ConsultaPTPCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConsultaRUC", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PersonaRUC ConsultaRUC(Usuario user, string RUC) {
            object[] results = this.Invoke("ConsultaRUC", new object[] {
                        user,
                        RUC});
            return ((PersonaRUC)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaRUCAsync(Usuario user, string RUC) {
            this.ConsultaRUCAsync(user, RUC, null);
        }
        
        /// <remarks/>
        public void ConsultaRUCAsync(Usuario user, string RUC, object userState) {
            if ((this.ConsultaRUCOperationCompleted == null)) {
                this.ConsultaRUCOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaRUCOperationCompleted);
            }
            this.InvokeAsync("ConsultaRUC", new object[] {
                        user,
                        RUC}, this.ConsultaRUCOperationCompleted, userState);
        }
        
        private void OnConsultaRUCOperationCompleted(object arg) {
            if ((this.ConsultaRUCCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaRUCCompleted(this, new ConsultaRUCCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConsultaToken", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Token ConsultaToken() {
            object[] results = this.Invoke("ConsultaToken", new object[0]);
            return ((Token)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaTokenAsync() {
            this.ConsultaTokenAsync(null);
        }
        
        /// <remarks/>
        public void ConsultaTokenAsync(object userState) {
            if ((this.ConsultaTokenOperationCompleted == null)) {
                this.ConsultaTokenOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaTokenOperationCompleted);
            }
            this.InvokeAsync("ConsultaToken", new object[0], this.ConsultaTokenOperationCompleted, userState);
        }
        
        private void OnConsultaTokenOperationCompleted(object arg) {
            if ((this.ConsultaTokenCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaTokenCompleted(this, new ConsultaTokenCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConsultaCITV", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CITV ConsultaCITV(Usuario user, string Placa) {
            object[] results = this.Invoke("ConsultaCITV", new object[] {
                        user,
                        Placa});
            return ((CITV)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaCITVAsync(Usuario user, string Placa) {
            this.ConsultaCITVAsync(user, Placa, null);
        }
        
        /// <remarks/>
        public void ConsultaCITVAsync(Usuario user, string Placa, object userState) {
            if ((this.ConsultaCITVOperationCompleted == null)) {
                this.ConsultaCITVOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaCITVOperationCompleted);
            }
            this.InvokeAsync("ConsultaCITV", new object[] {
                        user,
                        Placa}, this.ConsultaCITVOperationCompleted, userState);
        }
        
        private void OnConsultaCITVOperationCompleted(object arg) {
            if ((this.ConsultaCITVCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaCITVCompleted(this, new ConsultaCITVCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConsultaSOAT", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Soat ConsultaSOAT(Usuario user, string PLACA) {
            object[] results = this.Invoke("ConsultaSOAT", new object[] {
                        user,
                        PLACA});
            return ((Soat)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaSOATAsync(Usuario user, string PLACA) {
            this.ConsultaSOATAsync(user, PLACA, null);
        }
        
        /// <remarks/>
        public void ConsultaSOATAsync(Usuario user, string PLACA, object userState) {
            if ((this.ConsultaSOATOperationCompleted == null)) {
                this.ConsultaSOATOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaSOATOperationCompleted);
            }
            this.InvokeAsync("ConsultaSOAT", new object[] {
                        user,
                        PLACA}, this.ConsultaSOATOperationCompleted, userState);
        }
        
        private void OnConsultaSOATOperationCompleted(object arg) {
            if ((this.ConsultaSOATCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaSOATCompleted(this, new ConsultaSOATCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConsultaPapeleta", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Papeletas[] ConsultaPapeleta(Usuario user, string DNI, string TIPDOC) {
            object[] results = this.Invoke("ConsultaPapeleta", new object[] {
                        user,
                        DNI,
                        TIPDOC});
            return ((Papeletas[])(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaPapeletaAsync(Usuario user, string DNI, string TIPDOC) {
            this.ConsultaPapeletaAsync(user, DNI, TIPDOC, null);
        }
        
        /// <remarks/>
        public void ConsultaPapeletaAsync(Usuario user, string DNI, string TIPDOC, object userState) {
            if ((this.ConsultaPapeletaOperationCompleted == null)) {
                this.ConsultaPapeletaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaPapeletaOperationCompleted);
            }
            this.InvokeAsync("ConsultaPapeleta", new object[] {
                        user,
                        DNI,
                        TIPDOC}, this.ConsultaPapeletaOperationCompleted, userState);
        }
        
        private void OnConsultaPapeletaOperationCompleted(object arg) {
            if ((this.ConsultaPapeletaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaPapeletaCompleted(this, new ConsultaPapeletaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Usuario {
        
        private string uSULOGField;
        
        private string uSUCONField;
        
        /// <remarks/>
        public string USULOG {
            get {
                return this.uSULOGField;
            }
            set {
                this.uSULOGField = value;
            }
        }
        
        /// <remarks/>
        public string USUCON {
            get {
                return this.uSUCONField;
            }
            set {
                this.uSUCONField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Papeletas {
        
        private string eNTIDADField;
        
        private string pAPELETAField;
        
        private string fECHA_RESField;
        
        private string fECHA_FIRMEField;
        
        private string fALTAField;
        
        private string rESOLUCIONField;
        
        private double pUNTOS_FIRMEField;
        
        private double pUNTOS_PROCESOField;
        
        /// <remarks/>
        public string ENTIDAD {
            get {
                return this.eNTIDADField;
            }
            set {
                this.eNTIDADField = value;
            }
        }
        
        /// <remarks/>
        public string PAPELETA {
            get {
                return this.pAPELETAField;
            }
            set {
                this.pAPELETAField = value;
            }
        }
        
        /// <remarks/>
        public string FECHA_RES {
            get {
                return this.fECHA_RESField;
            }
            set {
                this.fECHA_RESField = value;
            }
        }
        
        /// <remarks/>
        public string FECHA_FIRME {
            get {
                return this.fECHA_FIRMEField;
            }
            set {
                this.fECHA_FIRMEField = value;
            }
        }
        
        /// <remarks/>
        public string FALTA {
            get {
                return this.fALTAField;
            }
            set {
                this.fALTAField = value;
            }
        }
        
        /// <remarks/>
        public string RESOLUCION {
            get {
                return this.rESOLUCIONField;
            }
            set {
                this.rESOLUCIONField = value;
            }
        }
        
        /// <remarks/>
        public double PUNTOS_FIRME {
            get {
                return this.pUNTOS_FIRMEField;
            }
            set {
                this.pUNTOS_FIRMEField = value;
            }
        }
        
        /// <remarks/>
        public double PUNTOS_PROCESO {
            get {
                return this.pUNTOS_PROCESOField;
            }
            set {
                this.pUNTOS_PROCESOField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Soat {
        
        private string companiaField;
        
        private string inivigenField;
        
        private string finvigenField;
        
        private string polcertiField;
        
        private string nroplacaField;
        
        private string contrataField;
        
        private string descrusoField;
        
        private string desclaseField;
        
        private string nromotorField;
        
        private string nrochasiField;
        
        /// <remarks/>
        public string compania {
            get {
                return this.companiaField;
            }
            set {
                this.companiaField = value;
            }
        }
        
        /// <remarks/>
        public string inivigen {
            get {
                return this.inivigenField;
            }
            set {
                this.inivigenField = value;
            }
        }
        
        /// <remarks/>
        public string finvigen {
            get {
                return this.finvigenField;
            }
            set {
                this.finvigenField = value;
            }
        }
        
        /// <remarks/>
        public string polcerti {
            get {
                return this.polcertiField;
            }
            set {
                this.polcertiField = value;
            }
        }
        
        /// <remarks/>
        public string nroplaca {
            get {
                return this.nroplacaField;
            }
            set {
                this.nroplacaField = value;
            }
        }
        
        /// <remarks/>
        public string contrata {
            get {
                return this.contrataField;
            }
            set {
                this.contrataField = value;
            }
        }
        
        /// <remarks/>
        public string descruso {
            get {
                return this.descrusoField;
            }
            set {
                this.descrusoField = value;
            }
        }
        
        /// <remarks/>
        public string desclase {
            get {
                return this.desclaseField;
            }
            set {
                this.desclaseField = value;
            }
        }
        
        /// <remarks/>
        public string nromotor {
            get {
                return this.nromotorField;
            }
            set {
                this.nromotorField = value;
            }
        }
        
        /// <remarks/>
        public string nrochasi {
            get {
                return this.nrochasiField;
            }
            set {
                this.nrochasiField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CITVRESULT {
        
        private string placaField;
        
        private string nro_certificadoField;
        
        private string vigente_desdeField;
        
        private string vigente_HastaField;
        
        private string resultado_InspeccionField;
        
        private string estadoField;
        
        private string empresa_certificadoraField;
        
        private string mensajeField;
        
        private string okField;
        
        /// <remarks/>
        public string Placa {
            get {
                return this.placaField;
            }
            set {
                this.placaField = value;
            }
        }
        
        /// <remarks/>
        public string Nro_certificado {
            get {
                return this.nro_certificadoField;
            }
            set {
                this.nro_certificadoField = value;
            }
        }
        
        /// <remarks/>
        public string Vigente_desde {
            get {
                return this.vigente_desdeField;
            }
            set {
                this.vigente_desdeField = value;
            }
        }
        
        /// <remarks/>
        public string Vigente_Hasta {
            get {
                return this.vigente_HastaField;
            }
            set {
                this.vigente_HastaField = value;
            }
        }
        
        /// <remarks/>
        public string Resultado_Inspeccion {
            get {
                return this.resultado_InspeccionField;
            }
            set {
                this.resultado_InspeccionField = value;
            }
        }
        
        /// <remarks/>
        public string Estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
            }
        }
        
        /// <remarks/>
        public string Empresa_certificadora {
            get {
                return this.empresa_certificadoraField;
            }
            set {
                this.empresa_certificadoraField = value;
            }
        }
        
        /// <remarks/>
        public string Mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
            }
        }
        
        /// <remarks/>
        public string Ok {
            get {
                return this.okField;
            }
            set {
                this.okField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CITV {
        
        private CITVRESULT resultField;
        
        /// <remarks/>
        public CITVRESULT result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Token {
        
        private string usernameField;
        
        private string passwordField;
        
        private string resultField;
        
        private bool successField;
        
        private string errorField;
        
        private int httpstatuscodeField;
        
        /// <remarks/>
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public string result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
        
        /// <remarks/>
        public bool success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        public string error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
            }
        }
        
        /// <remarks/>
        public int httpstatuscode {
            get {
                return this.httpstatuscodeField;
            }
            set {
                this.httpstatuscodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class PersonaRUC {
        
        private string ddp_nombreField;
        
        private string ddp_numrucField;
        
        private string desc_estadoField;
        
        /// <remarks/>
        public string ddp_nombre {
            get {
                return this.ddp_nombreField;
            }
            set {
                this.ddp_nombreField = value;
            }
        }
        
        /// <remarks/>
        public string ddp_numruc {
            get {
                return this.ddp_numrucField;
            }
            set {
                this.ddp_numrucField = value;
            }
        }
        
        /// <remarks/>
        public string desc_estado {
            get {
                return this.desc_estadoField;
            }
            set {
                this.desc_estadoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class PermiTempPerm {
        
        private string nUM_DOCUMENTOField;
        
        private string nOMBREField;
        
        private string aPE_PATERNOField;
        
        private string aPE_MATERNOField;
        
        private string cATEGORIAField;
        
        private string fECREVField;
        
        private string nUM_LICENCIAField;
        
        private string eSTADOField;
        
        private string rESTRICCIONField;
        
        private string fECEXPField;
        
        /// <remarks/>
        public string NUM_DOCUMENTO {
            get {
                return this.nUM_DOCUMENTOField;
            }
            set {
                this.nUM_DOCUMENTOField = value;
            }
        }
        
        /// <remarks/>
        public string NOMBRE {
            get {
                return this.nOMBREField;
            }
            set {
                this.nOMBREField = value;
            }
        }
        
        /// <remarks/>
        public string APE_PATERNO {
            get {
                return this.aPE_PATERNOField;
            }
            set {
                this.aPE_PATERNOField = value;
            }
        }
        
        /// <remarks/>
        public string APE_MATERNO {
            get {
                return this.aPE_MATERNOField;
            }
            set {
                this.aPE_MATERNOField = value;
            }
        }
        
        /// <remarks/>
        public string CATEGORIA {
            get {
                return this.cATEGORIAField;
            }
            set {
                this.cATEGORIAField = value;
            }
        }
        
        /// <remarks/>
        public string FECREV {
            get {
                return this.fECREVField;
            }
            set {
                this.fECREVField = value;
            }
        }
        
        /// <remarks/>
        public string NUM_LICENCIA {
            get {
                return this.nUM_LICENCIAField;
            }
            set {
                this.nUM_LICENCIAField = value;
            }
        }
        
        /// <remarks/>
        public string ESTADO {
            get {
                return this.eSTADOField;
            }
            set {
                this.eSTADOField = value;
            }
        }
        
        /// <remarks/>
        public string RESTRICCION {
            get {
                return this.rESTRICCIONField;
            }
            set {
                this.rESTRICCIONField = value;
            }
        }
        
        /// <remarks/>
        public string FECEXP {
            get {
                return this.fECEXPField;
            }
            set {
                this.fECEXPField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Migraciones {
        
        private string strNombresField;
        
        private string strPrimerApellidoField;
        
        private string strSegundoApellidoField;
        
        private string strCalidadMigratoriaField;
        
        private string strNumRespuestaField;
        
        /// <remarks/>
        public string strNombres {
            get {
                return this.strNombresField;
            }
            set {
                this.strNombresField = value;
            }
        }
        
        /// <remarks/>
        public string strPrimerApellido {
            get {
                return this.strPrimerApellidoField;
            }
            set {
                this.strPrimerApellidoField = value;
            }
        }
        
        /// <remarks/>
        public string strSegundoApellido {
            get {
                return this.strSegundoApellidoField;
            }
            set {
                this.strSegundoApellidoField = value;
            }
        }
        
        /// <remarks/>
        public string strCalidadMigratoria {
            get {
                return this.strCalidadMigratoriaField;
            }
            set {
                this.strCalidadMigratoriaField = value;
            }
        }
        
        /// <remarks/>
        public string strNumRespuesta {
            get {
                return this.strNumRespuestaField;
            }
            set {
                this.strNumRespuestaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Vehiculo {
        
        private string placaField;
        
        private string serieField;
        
        private string vinField;
        
        private string nro_motorField;
        
        private string colorField;
        
        private string marcaField;
        
        private string modeloField;
        
        private string estadoField;
        
        private string sedeField;
        
        private string[] propietariosField;
        
        private string[] nombreField;
        
        private string propietarioField;
        
        /// <remarks/>
        public string placa {
            get {
                return this.placaField;
            }
            set {
                this.placaField = value;
            }
        }
        
        /// <remarks/>
        public string serie {
            get {
                return this.serieField;
            }
            set {
                this.serieField = value;
            }
        }
        
        /// <remarks/>
        public string vin {
            get {
                return this.vinField;
            }
            set {
                this.vinField = value;
            }
        }
        
        /// <remarks/>
        public string nro_motor {
            get {
                return this.nro_motorField;
            }
            set {
                this.nro_motorField = value;
            }
        }
        
        /// <remarks/>
        public string color {
            get {
                return this.colorField;
            }
            set {
                this.colorField = value;
            }
        }
        
        /// <remarks/>
        public string marca {
            get {
                return this.marcaField;
            }
            set {
                this.marcaField = value;
            }
        }
        
        /// <remarks/>
        public string modelo {
            get {
                return this.modeloField;
            }
            set {
                this.modeloField = value;
            }
        }
        
        /// <remarks/>
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
            }
        }
        
        /// <remarks/>
        public string sede {
            get {
                return this.sedeField;
            }
            set {
                this.sedeField = value;
            }
        }
        
        /// <remarks/>
        public string[] propietarios {
            get {
                return this.propietariosField;
            }
            set {
                this.propietariosField = value;
            }
        }
        
        /// <remarks/>
        public string[] nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        public string propietario {
            get {
                return this.propietarioField;
            }
            set {
                this.propietarioField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Conductor {
        
        private string dniField;
        
        private string nUM_LICENCIAField;
        
        private string cATEGORIAField;
        
        private string fECREVField;
        
        private string eSTADOField;
        
        private string tIPO_DOCField;
        
        private string nUM_DOCUMENTOField;
        
        private string aPE_PATERNOField;
        
        private string aPE_MATERNOField;
        
        private string nOMBREField;
        
        private string rESTRICCIONField;
        
        private string fECEXPField;
        
        /// <remarks/>
        public string dni {
            get {
                return this.dniField;
            }
            set {
                this.dniField = value;
            }
        }
        
        /// <remarks/>
        public string NUM_LICENCIA {
            get {
                return this.nUM_LICENCIAField;
            }
            set {
                this.nUM_LICENCIAField = value;
            }
        }
        
        /// <remarks/>
        public string CATEGORIA {
            get {
                return this.cATEGORIAField;
            }
            set {
                this.cATEGORIAField = value;
            }
        }
        
        /// <remarks/>
        public string FECREV {
            get {
                return this.fECREVField;
            }
            set {
                this.fECREVField = value;
            }
        }
        
        /// <remarks/>
        public string ESTADO {
            get {
                return this.eSTADOField;
            }
            set {
                this.eSTADOField = value;
            }
        }
        
        /// <remarks/>
        public string TIPO_DOC {
            get {
                return this.tIPO_DOCField;
            }
            set {
                this.tIPO_DOCField = value;
            }
        }
        
        /// <remarks/>
        public string NUM_DOCUMENTO {
            get {
                return this.nUM_DOCUMENTOField;
            }
            set {
                this.nUM_DOCUMENTOField = value;
            }
        }
        
        /// <remarks/>
        public string APE_PATERNO {
            get {
                return this.aPE_PATERNOField;
            }
            set {
                this.aPE_PATERNOField = value;
            }
        }
        
        /// <remarks/>
        public string APE_MATERNO {
            get {
                return this.aPE_MATERNOField;
            }
            set {
                this.aPE_MATERNOField = value;
            }
        }
        
        /// <remarks/>
        public string NOMBRE {
            get {
                return this.nOMBREField;
            }
            set {
                this.nOMBREField = value;
            }
        }
        
        /// <remarks/>
        public string RESTRICCION {
            get {
                return this.rESTRICCIONField;
            }
            set {
                this.rESTRICCIONField = value;
            }
        }
        
        /// <remarks/>
        public string FECEXP {
            get {
                return this.fECEXPField;
            }
            set {
                this.fECEXPField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Persona {
        
        private string apPrimerField;
        
        private string apSegundoField;
        
        private string direccionField;
        
        private string estadoCivilField;
        
        private string fotoField;
        
        private string prenombresField;
        
        private string restriccionField;
        
        private string ubigeoField;
        
        /// <remarks/>
        public string apPrimer {
            get {
                return this.apPrimerField;
            }
            set {
                this.apPrimerField = value;
            }
        }
        
        /// <remarks/>
        public string apSegundo {
            get {
                return this.apSegundoField;
            }
            set {
                this.apSegundoField = value;
            }
        }
        
        /// <remarks/>
        public string direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
            }
        }
        
        /// <remarks/>
        public string estadoCivil {
            get {
                return this.estadoCivilField;
            }
            set {
                this.estadoCivilField = value;
            }
        }
        
        /// <remarks/>
        public string foto {
            get {
                return this.fotoField;
            }
            set {
                this.fotoField = value;
            }
        }
        
        /// <remarks/>
        public string prenombres {
            get {
                return this.prenombresField;
            }
            set {
                this.prenombresField = value;
            }
        }
        
        /// <remarks/>
        public string restriccion {
            get {
                return this.restriccionField;
            }
            set {
                this.restriccionField = value;
            }
        }
        
        /// <remarks/>
        public string ubigeo {
            get {
                return this.ubigeoField;
            }
            set {
                this.ubigeoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void ConsultaDNICompletedEventHandler(object sender, ConsultaDNICompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaDNICompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaDNICompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Persona Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Persona)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void ConsultaLicenciaCompletedEventHandler(object sender, ConsultaLicenciaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaLicenciaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaLicenciaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Conductor Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Conductor)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void ConsultaPlacaCompletedEventHandler(object sender, ConsultaPlacaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaPlacaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaPlacaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Vehiculo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Vehiculo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void ConsulMigraCompletedEventHandler(object sender, ConsulMigraCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsulMigraCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsulMigraCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Migraciones Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Migraciones)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void ConsultaPTPCompletedEventHandler(object sender, ConsultaPTPCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaPTPCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaPTPCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PermiTempPerm Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PermiTempPerm)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void ConsultaRUCCompletedEventHandler(object sender, ConsultaRUCCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaRUCCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaRUCCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PersonaRUC Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PersonaRUC)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void ConsultaTokenCompletedEventHandler(object sender, ConsultaTokenCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaTokenCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaTokenCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Token Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Token)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void ConsultaCITVCompletedEventHandler(object sender, ConsultaCITVCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaCITVCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaCITVCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CITV Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CITV)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void ConsultaSOATCompletedEventHandler(object sender, ConsultaSOATCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaSOATCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaSOATCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Soat Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Soat)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void ConsultaPapeletaCompletedEventHandler(object sender, ConsultaPapeletaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaPapeletaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaPapeletaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Papeletas[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Papeletas[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591