//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace SisATU.Servicios.Servicio_STD {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Servicio_STDSoap", Namespace="http://tempuri.org/")]
    public partial class Servicio_STD : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback BuscarProveedorOperationCompleted;
        
        private System.Threading.SendOrPostCallback BuscarPersonaOperationCompleted;
        
        private System.Threading.SendOrPostCallback AgregarProveedorOperationCompleted;
        
        private System.Threading.SendOrPostCallback AgregarPersonaOperationCompleted;
        
        private System.Threading.SendOrPostCallback AgregarHojaRutaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ActualizarHojaRutaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarProcedimientoOperationCompleted;
        
        private System.Threading.SendOrPostCallback CuentaPasosOperationCompleted;
        
        private System.Threading.SendOrPostCallback AgregarAcumuladorOperationCompleted;
        
        private System.Threading.SendOrPostCallback Generar_ResolucionOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Servicio_STD() {
            this.Url = global::SisATU.Servicios.Properties.Settings.Default.SisATU_Servicios_Servicio_STD_Servicio_STD;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event BuscarProveedorCompletedEventHandler BuscarProveedorCompleted;
        
        /// <remarks/>
        public event BuscarPersonaCompletedEventHandler BuscarPersonaCompleted;
        
        /// <remarks/>
        public event AgregarProveedorCompletedEventHandler AgregarProveedorCompleted;
        
        /// <remarks/>
        public event AgregarPersonaCompletedEventHandler AgregarPersonaCompleted;
        
        /// <remarks/>
        public event AgregarHojaRutaCompletedEventHandler AgregarHojaRutaCompleted;
        
        /// <remarks/>
        public event ActualizarHojaRutaCompletedEventHandler ActualizarHojaRutaCompleted;
        
        /// <remarks/>
        public event ListarProcedimientoCompletedEventHandler ListarProcedimientoCompleted;
        
        /// <remarks/>
        public event CuentaPasosCompletedEventHandler CuentaPasosCompleted;
        
        /// <remarks/>
        public event AgregarAcumuladorCompletedEventHandler AgregarAcumuladorCompleted;
        
        /// <remarks/>
        public event Generar_ResolucionCompletedEventHandler Generar_ResolucionCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BuscarProveedor", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Proveedor BuscarProveedor(Proveedor objeto) {
            object[] results = this.Invoke("BuscarProveedor", new object[] {
                        objeto});
            return ((Proveedor)(results[0]));
        }
        
        /// <remarks/>
        public void BuscarProveedorAsync(Proveedor objeto) {
            this.BuscarProveedorAsync(objeto, null);
        }
        
        /// <remarks/>
        public void BuscarProveedorAsync(Proveedor objeto, object userState) {
            if ((this.BuscarProveedorOperationCompleted == null)) {
                this.BuscarProveedorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBuscarProveedorOperationCompleted);
            }
            this.InvokeAsync("BuscarProveedor", new object[] {
                        objeto}, this.BuscarProveedorOperationCompleted, userState);
        }
        
        private void OnBuscarProveedorOperationCompleted(object arg) {
            if ((this.BuscarProveedorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BuscarProveedorCompleted(this, new BuscarProveedorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BuscarPersona", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Persona BuscarPersona(Usuario usuario, Persona objeto) {
            object[] results = this.Invoke("BuscarPersona", new object[] {
                        usuario,
                        objeto});
            return ((Persona)(results[0]));
        }
        
        /// <remarks/>
        public void BuscarPersonaAsync(Usuario usuario, Persona objeto) {
            this.BuscarPersonaAsync(usuario, objeto, null);
        }
        
        /// <remarks/>
        public void BuscarPersonaAsync(Usuario usuario, Persona objeto, object userState) {
            if ((this.BuscarPersonaOperationCompleted == null)) {
                this.BuscarPersonaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBuscarPersonaOperationCompleted);
            }
            this.InvokeAsync("BuscarPersona", new object[] {
                        usuario,
                        objeto}, this.BuscarPersonaOperationCompleted, userState);
        }
        
        private void OnBuscarPersonaOperationCompleted(object arg) {
            if ((this.BuscarPersonaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BuscarPersonaCompleted(this, new BuscarPersonaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AgregarProveedor", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Proveedor AgregarProveedor(Usuario usuario, Proveedor objeto) {
            object[] results = this.Invoke("AgregarProveedor", new object[] {
                        usuario,
                        objeto});
            return ((Proveedor)(results[0]));
        }
        
        /// <remarks/>
        public void AgregarProveedorAsync(Usuario usuario, Proveedor objeto) {
            this.AgregarProveedorAsync(usuario, objeto, null);
        }
        
        /// <remarks/>
        public void AgregarProveedorAsync(Usuario usuario, Proveedor objeto, object userState) {
            if ((this.AgregarProveedorOperationCompleted == null)) {
                this.AgregarProveedorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAgregarProveedorOperationCompleted);
            }
            this.InvokeAsync("AgregarProveedor", new object[] {
                        usuario,
                        objeto}, this.AgregarProveedorOperationCompleted, userState);
        }
        
        private void OnAgregarProveedorOperationCompleted(object arg) {
            if ((this.AgregarProveedorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AgregarProveedorCompleted(this, new AgregarProveedorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AgregarPersona", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Persona AgregarPersona(Usuario usuario, Persona objeto) {
            object[] results = this.Invoke("AgregarPersona", new object[] {
                        usuario,
                        objeto});
            return ((Persona)(results[0]));
        }
        
        /// <remarks/>
        public void AgregarPersonaAsync(Usuario usuario, Persona objeto) {
            this.AgregarPersonaAsync(usuario, objeto, null);
        }
        
        /// <remarks/>
        public void AgregarPersonaAsync(Usuario usuario, Persona objeto, object userState) {
            if ((this.AgregarPersonaOperationCompleted == null)) {
                this.AgregarPersonaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAgregarPersonaOperationCompleted);
            }
            this.InvokeAsync("AgregarPersona", new object[] {
                        usuario,
                        objeto}, this.AgregarPersonaOperationCompleted, userState);
        }
        
        private void OnAgregarPersonaOperationCompleted(object arg) {
            if ((this.AgregarPersonaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AgregarPersonaCompleted(this, new AgregarPersonaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AgregarHojaRuta", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public HojaRuta AgregarHojaRuta(HojaRuta objeto) {
            object[] results = this.Invoke("AgregarHojaRuta", new object[] {
                        objeto});
            return ((HojaRuta)(results[0]));
        }
        
        /// <remarks/>
        public void AgregarHojaRutaAsync(HojaRuta objeto) {
            this.AgregarHojaRutaAsync(objeto, null);
        }
        
        /// <remarks/>
        public void AgregarHojaRutaAsync(HojaRuta objeto, object userState) {
            if ((this.AgregarHojaRutaOperationCompleted == null)) {
                this.AgregarHojaRutaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAgregarHojaRutaOperationCompleted);
            }
            this.InvokeAsync("AgregarHojaRuta", new object[] {
                        objeto}, this.AgregarHojaRutaOperationCompleted, userState);
        }
        
        private void OnAgregarHojaRutaOperationCompleted(object arg) {
            if ((this.AgregarHojaRutaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AgregarHojaRutaCompleted(this, new AgregarHojaRutaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ActualizarHojaRuta", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public cerrar ActualizarHojaRuta(cerrar objeto) {
            object[] results = this.Invoke("ActualizarHojaRuta", new object[] {
                        objeto});
            return ((cerrar)(results[0]));
        }
        
        /// <remarks/>
        public void ActualizarHojaRutaAsync(cerrar objeto) {
            this.ActualizarHojaRutaAsync(objeto, null);
        }
        
        /// <remarks/>
        public void ActualizarHojaRutaAsync(cerrar objeto, object userState) {
            if ((this.ActualizarHojaRutaOperationCompleted == null)) {
                this.ActualizarHojaRutaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnActualizarHojaRutaOperationCompleted);
            }
            this.InvokeAsync("ActualizarHojaRuta", new object[] {
                        objeto}, this.ActualizarHojaRutaOperationCompleted, userState);
        }
        
        private void OnActualizarHojaRutaOperationCompleted(object arg) {
            if ((this.ActualizarHojaRutaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ActualizarHojaRutaCompleted(this, new ActualizarHojaRutaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ListarProcedimiento", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Procedimiento[] ListarProcedimiento(Usuario usuario, string TIPO) {
            object[] results = this.Invoke("ListarProcedimiento", new object[] {
                        usuario,
                        TIPO});
            return ((Procedimiento[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarProcedimientoAsync(Usuario usuario, string TIPO) {
            this.ListarProcedimientoAsync(usuario, TIPO, null);
        }
        
        /// <remarks/>
        public void ListarProcedimientoAsync(Usuario usuario, string TIPO, object userState) {
            if ((this.ListarProcedimientoOperationCompleted == null)) {
                this.ListarProcedimientoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarProcedimientoOperationCompleted);
            }
            this.InvokeAsync("ListarProcedimiento", new object[] {
                        usuario,
                        TIPO}, this.ListarProcedimientoOperationCompleted, userState);
        }
        
        private void OnListarProcedimientoOperationCompleted(object arg) {
            if ((this.ListarProcedimientoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarProcedimientoCompleted(this, new ListarProcedimientoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CuentaPasos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int CuentaPasos(Usuario usuario, int IDDOC) {
            object[] results = this.Invoke("CuentaPasos", new object[] {
                        usuario,
                        IDDOC});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void CuentaPasosAsync(Usuario usuario, int IDDOC) {
            this.CuentaPasosAsync(usuario, IDDOC, null);
        }
        
        /// <remarks/>
        public void CuentaPasosAsync(Usuario usuario, int IDDOC, object userState) {
            if ((this.CuentaPasosOperationCompleted == null)) {
                this.CuentaPasosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCuentaPasosOperationCompleted);
            }
            this.InvokeAsync("CuentaPasos", new object[] {
                        usuario,
                        IDDOC}, this.CuentaPasosOperationCompleted, userState);
        }
        
        private void OnCuentaPasosOperationCompleted(object arg) {
            if ((this.CuentaPasosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CuentaPasosCompleted(this, new CuentaPasosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AgregarAcumulador", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Acumulador AgregarAcumulador(Acumulador objeto) {
            object[] results = this.Invoke("AgregarAcumulador", new object[] {
                        objeto});
            return ((Acumulador)(results[0]));
        }
        
        /// <remarks/>
        public void AgregarAcumuladorAsync(Acumulador objeto) {
            this.AgregarAcumuladorAsync(objeto, null);
        }
        
        /// <remarks/>
        public void AgregarAcumuladorAsync(Acumulador objeto, object userState) {
            if ((this.AgregarAcumuladorOperationCompleted == null)) {
                this.AgregarAcumuladorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAgregarAcumuladorOperationCompleted);
            }
            this.InvokeAsync("AgregarAcumulador", new object[] {
                        objeto}, this.AgregarAcumuladorOperationCompleted, userState);
        }
        
        private void OnAgregarAcumuladorOperationCompleted(object arg) {
            if ((this.AgregarAcumuladorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AgregarAcumuladorCompleted(this, new AgregarAcumuladorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Generar_Resolucion", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Resolucion Generar_Resolucion(Resolucion objeto) {
            object[] results = this.Invoke("Generar_Resolucion", new object[] {
                        objeto});
            return ((Resolucion)(results[0]));
        }
        
        /// <remarks/>
        public void Generar_ResolucionAsync(Resolucion objeto) {
            this.Generar_ResolucionAsync(objeto, null);
        }
        
        /// <remarks/>
        public void Generar_ResolucionAsync(Resolucion objeto, object userState) {
            if ((this.Generar_ResolucionOperationCompleted == null)) {
                this.Generar_ResolucionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGenerar_ResolucionOperationCompleted);
            }
            this.InvokeAsync("Generar_Resolucion", new object[] {
                        objeto}, this.Generar_ResolucionOperationCompleted, userState);
        }
        
        private void OnGenerar_ResolucionOperationCompleted(object arg) {
            if ((this.Generar_ResolucionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Generar_ResolucionCompleted(this, new Generar_ResolucionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Proveedor {
        
        private System.Nullable<long> iDPROVEEField;
        
        private System.Nullable<long> iDPERTIPField;
        
        private string rAZON_SOCIALField;
        
        private string rUCField;
        
        private System.Nullable<long> cODPAISField;
        
        private System.Nullable<short> cODDPTOField;
        
        private System.Nullable<short> cODPROVField;
        
        private System.Nullable<short> cODDISTField;
        
        private string dIRECCIONField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> IDPROVEE {
            get {
                return this.iDPROVEEField;
            }
            set {
                this.iDPROVEEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> IDPERTIP {
            get {
                return this.iDPERTIPField;
            }
            set {
                this.iDPERTIPField = value;
            }
        }
        
        /// <remarks/>
        public string RAZON_SOCIAL {
            get {
                return this.rAZON_SOCIALField;
            }
            set {
                this.rAZON_SOCIALField = value;
            }
        }
        
        /// <remarks/>
        public string RUC {
            get {
                return this.rUCField;
            }
            set {
                this.rUCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> CODPAIS {
            get {
                return this.cODPAISField;
            }
            set {
                this.cODPAISField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<short> CODDPTO {
            get {
                return this.cODDPTOField;
            }
            set {
                this.cODDPTOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<short> CODPROV {
            get {
                return this.cODPROVField;
            }
            set {
                this.cODPROVField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<short> CODDIST {
            get {
                return this.cODDISTField;
            }
            set {
                this.cODDISTField = value;
            }
        }
        
        /// <remarks/>
        public string DIRECCION {
            get {
                return this.dIRECCIONField;
            }
            set {
                this.dIRECCIONField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Resolucion {
        
        private System.Nullable<int> iDUNIDADField;
        
        private System.Nullable<int> iDCLASEField;
        
        private string nUMEROCLASEField;
        
        private System.Nullable<int> nUMEROANIOField;
        
        private string aSUNTOField;
        
        private string cOMENTARIOField;
        
        private string fECHA_DOCField;
        
        private string pARAField;
        
        private string pARAFUNCIONARIOField;
        
        private string rEFERENCIAField;
        
        private System.Nullable<int> iDDOCField;
        
        private System.Nullable<int> iDFLUJOField;
        
        private System.Nullable<int> iDUSER_PROYECTO_DOCField;
        
        private System.Nullable<int> iDUSER_CREAField;
        
        private string eSTADOField;
        
        private System.Nullable<int> iDCRTLNUMField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> IDUNIDAD {
            get {
                return this.iDUNIDADField;
            }
            set {
                this.iDUNIDADField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> IDCLASE {
            get {
                return this.iDCLASEField;
            }
            set {
                this.iDCLASEField = value;
            }
        }
        
        /// <remarks/>
        public string NUMEROCLASE {
            get {
                return this.nUMEROCLASEField;
            }
            set {
                this.nUMEROCLASEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> NUMEROANIO {
            get {
                return this.nUMEROANIOField;
            }
            set {
                this.nUMEROANIOField = value;
            }
        }
        
        /// <remarks/>
        public string ASUNTO {
            get {
                return this.aSUNTOField;
            }
            set {
                this.aSUNTOField = value;
            }
        }
        
        /// <remarks/>
        public string COMENTARIO {
            get {
                return this.cOMENTARIOField;
            }
            set {
                this.cOMENTARIOField = value;
            }
        }
        
        /// <remarks/>
        public string FECHA_DOC {
            get {
                return this.fECHA_DOCField;
            }
            set {
                this.fECHA_DOCField = value;
            }
        }
        
        /// <remarks/>
        public string PARA {
            get {
                return this.pARAField;
            }
            set {
                this.pARAField = value;
            }
        }
        
        /// <remarks/>
        public string PARAFUNCIONARIO {
            get {
                return this.pARAFUNCIONARIOField;
            }
            set {
                this.pARAFUNCIONARIOField = value;
            }
        }
        
        /// <remarks/>
        public string REFERENCIA {
            get {
                return this.rEFERENCIAField;
            }
            set {
                this.rEFERENCIAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> IDDOC {
            get {
                return this.iDDOCField;
            }
            set {
                this.iDDOCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> IDFLUJO {
            get {
                return this.iDFLUJOField;
            }
            set {
                this.iDFLUJOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> IDUSER_PROYECTO_DOC {
            get {
                return this.iDUSER_PROYECTO_DOCField;
            }
            set {
                this.iDUSER_PROYECTO_DOCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> IDUSER_CREA {
            get {
                return this.iDUSER_CREAField;
            }
            set {
                this.iDUSER_CREAField = value;
            }
        }
        
        /// <remarks/>
        public string ESTADO {
            get {
                return this.eSTADOField;
            }
            set {
                this.eSTADOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> IDCRTLNUM {
            get {
                return this.iDCRTLNUMField;
            }
            set {
                this.iDCRTLNUMField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Acumulador {
        
        private System.Nullable<int> iDDOC_PADREField;
        
        private System.Nullable<int> iDDOC_HIJOField;
        
        private System.Nullable<int> iDFLUJO_HIJOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> IDDOC_PADRE {
            get {
                return this.iDDOC_PADREField;
            }
            set {
                this.iDDOC_PADREField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> IDDOC_HIJO {
            get {
                return this.iDDOC_HIJOField;
            }
            set {
                this.iDDOC_HIJOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> IDFLUJO_HIJO {
            get {
                return this.iDFLUJO_HIJOField;
            }
            set {
                this.iDFLUJO_HIJOField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Procedimiento {
        
        private System.Nullable<long> iDPROCField;
        
        private string pROCEDIMIENTOField;
        
        private System.Nullable<long> iDUNIDADField;
        
        private System.Nullable<decimal> pORCENTAJE_UITField;
        
        private System.Nullable<short> tIPO_EVALUACIONField;
        
        private System.Nullable<int> tOTAL_POSITIVOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> IDPROC {
            get {
                return this.iDPROCField;
            }
            set {
                this.iDPROCField = value;
            }
        }
        
        /// <remarks/>
        public string PROCEDIMIENTO {
            get {
                return this.pROCEDIMIENTOField;
            }
            set {
                this.pROCEDIMIENTOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> IDUNIDAD {
            get {
                return this.iDUNIDADField;
            }
            set {
                this.iDUNIDADField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> PORCENTAJE_UIT {
            get {
                return this.pORCENTAJE_UITField;
            }
            set {
                this.pORCENTAJE_UITField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<short> TIPO_EVALUACION {
            get {
                return this.tIPO_EVALUACIONField;
            }
            set {
                this.tIPO_EVALUACIONField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> TOTAL_POSITIVO {
            get {
                return this.tOTAL_POSITIVOField;
            }
            set {
                this.tOTAL_POSITIVOField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class cerrar {
        
        private string iDUNIDADField;
        
        private string oBSERVACIONField;
        
        private int iDDOCField;
        
        /// <remarks/>
        public string IDUNIDAD {
            get {
                return this.iDUNIDADField;
            }
            set {
                this.iDUNIDADField = value;
            }
        }
        
        /// <remarks/>
        public string OBSERVACION {
            get {
                return this.oBSERVACIONField;
            }
            set {
                this.oBSERVACIONField = value;
            }
        }
        
        /// <remarks/>
        public int IDDOC {
            get {
                return this.iDDOCField;
            }
            set {
                this.iDDOCField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class HojaRuta {
        
        private System.Nullable<int> iDDOCField;
        
        private string nUMERO_SIDField;
        
        private string nUMERO_ANIOField;
        
        private string nUMERO_DOCField;
        
        private System.Nullable<System.DateTime> fECHA_DOCUMENTOField;
        
        private System.Nullable<int> iDCLASEField;
        
        private System.Nullable<int> fOLIOS_INIField;
        
        private System.Nullable<int> fOLIOS_FINField;
        
        private string aSUNTOField;
        
        private System.Nullable<int> iDPROCField;
        
        private System.Nullable<int> tIEMPOESTADIAField;
        
        private System.Nullable<int> iDPERSONField;
        
        private System.Nullable<int> iDPROVEEField;
        
        private System.Nullable<int> pRIORIDADField;
        
        private System.Nullable<int> tIPOEXPEDIENTEField;
        
        private System.Nullable<int> iDSERIEField;
        
        private System.Nullable<int> iDUBIFISField;
        
        private System.Nullable<int> iDARCHMUEBField;
        
        private System.Nullable<int> iDARCHMEDField;
        
        private System.Nullable<int> iDUNIDADField;
        
        private System.Nullable<System.DateTime> fECHA_CREAField;
        
        private System.Nullable<System.DateTime> fECHA_MODIFField;
        
        private System.Nullable<int> iDUSER_CREAField;
        
        private System.Nullable<int> iDUSER_MODIFField;
        
        private System.Nullable<int> eSTADOField;
        
        private string nUMERO_DOC_FINField;
        
        private System.Nullable<System.DateTime> fECHA_DOC_FINField;
        
        private System.Nullable<int> iDCLASE_FINField;
        
        private System.Nullable<int> tIPO_FINField;
        
        private System.Nullable<System.DateTime> fECHA_SUSP_INICIOField;
        
        private System.Nullable<System.DateTime> fECHA_SUSP_FINField;
        
        private System.Nullable<int> iDDOC_ANEXADOField;
        
        private System.Nullable<int> sUBTIPOEXPEDIENTEField;
        
        private System.Nullable<int> uNIDADPROVEEField;
        
        private System.Nullable<System.DateTime> fECHA_COMPLETOField;
        
        private System.Nullable<int> cODPAISField;
        
        private System.Nullable<int> cODDPTOField;
        
        private System.Nullable<int> cODPROVField;
        
        private System.Nullable<int> cODDISTField;
        
        private string dIRECCIONField;
        
        private string oBSERV_DOC_FINField;
        
        private string iNSTITUCION_NO_REGField;
        
        private string aNEXOSField;
        
        private System.Nullable<int> iDFLUJOField;
        
        private string mensajeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> IDDOC {
            get {
                return this.iDDOCField;
            }
            set {
                this.iDDOCField = value;
            }
        }
        
        /// <remarks/>
        public string NUMERO_SID {
            get {
                return this.nUMERO_SIDField;
            }
            set {
                this.nUMERO_SIDField = value;
            }
        }
        
        /// <remarks/>
        public string NUMERO_ANIO {
            get {
                return this.nUMERO_ANIOField;
            }
            set {
                this.nUMERO_ANIOField = value;
            }
        }
        
        /// <remarks/>
        public string NUMERO_DOC {
            get {
                return this.nUMERO_DOCField;
            }
            set {
                this.nUMERO_DOCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> FECHA_DOCUMENTO {
            get {
                return this.fECHA_DOCUMENTOField;
            }
            set {
                this.fECHA_DOCUMENTOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> IDCLASE {
            get {
                return this.iDCLASEField;
            }
            set {
                this.iDCLASEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> FOLIOS_INI {
            get {
                return this.fOLIOS_INIField;
            }
            set {
                this.fOLIOS_INIField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> FOLIOS_FIN {
            get {
                return this.fOLIOS_FINField;
            }
            set {
                this.fOLIOS_FINField = value;
            }
        }
        
        /// <remarks/>
        public string ASUNTO {
            get {
                return this.aSUNTOField;
            }
            set {
                this.aSUNTOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> IDPROC {
            get {
                return this.iDPROCField;
            }
            set {
                this.iDPROCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> TIEMPOESTADIA {
            get {
                return this.tIEMPOESTADIAField;
            }
            set {
                this.tIEMPOESTADIAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> IDPERSON {
            get {
                return this.iDPERSONField;
            }
            set {
                this.iDPERSONField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> IDPROVEE {
            get {
                return this.iDPROVEEField;
            }
            set {
                this.iDPROVEEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> PRIORIDAD {
            get {
                return this.pRIORIDADField;
            }
            set {
                this.pRIORIDADField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> TIPOEXPEDIENTE {
            get {
                return this.tIPOEXPEDIENTEField;
            }
            set {
                this.tIPOEXPEDIENTEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> IDSERIE {
            get {
                return this.iDSERIEField;
            }
            set {
                this.iDSERIEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> IDUBIFIS {
            get {
                return this.iDUBIFISField;
            }
            set {
                this.iDUBIFISField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> IDARCHMUEB {
            get {
                return this.iDARCHMUEBField;
            }
            set {
                this.iDARCHMUEBField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> IDARCHMED {
            get {
                return this.iDARCHMEDField;
            }
            set {
                this.iDARCHMEDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> IDUNIDAD {
            get {
                return this.iDUNIDADField;
            }
            set {
                this.iDUNIDADField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> FECHA_CREA {
            get {
                return this.fECHA_CREAField;
            }
            set {
                this.fECHA_CREAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> FECHA_MODIF {
            get {
                return this.fECHA_MODIFField;
            }
            set {
                this.fECHA_MODIFField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> IDUSER_CREA {
            get {
                return this.iDUSER_CREAField;
            }
            set {
                this.iDUSER_CREAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> IDUSER_MODIF {
            get {
                return this.iDUSER_MODIFField;
            }
            set {
                this.iDUSER_MODIFField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> ESTADO {
            get {
                return this.eSTADOField;
            }
            set {
                this.eSTADOField = value;
            }
        }
        
        /// <remarks/>
        public string NUMERO_DOC_FIN {
            get {
                return this.nUMERO_DOC_FINField;
            }
            set {
                this.nUMERO_DOC_FINField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> FECHA_DOC_FIN {
            get {
                return this.fECHA_DOC_FINField;
            }
            set {
                this.fECHA_DOC_FINField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> IDCLASE_FIN {
            get {
                return this.iDCLASE_FINField;
            }
            set {
                this.iDCLASE_FINField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> TIPO_FIN {
            get {
                return this.tIPO_FINField;
            }
            set {
                this.tIPO_FINField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> FECHA_SUSP_INICIO {
            get {
                return this.fECHA_SUSP_INICIOField;
            }
            set {
                this.fECHA_SUSP_INICIOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> FECHA_SUSP_FIN {
            get {
                return this.fECHA_SUSP_FINField;
            }
            set {
                this.fECHA_SUSP_FINField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> IDDOC_ANEXADO {
            get {
                return this.iDDOC_ANEXADOField;
            }
            set {
                this.iDDOC_ANEXADOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> SUBTIPOEXPEDIENTE {
            get {
                return this.sUBTIPOEXPEDIENTEField;
            }
            set {
                this.sUBTIPOEXPEDIENTEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> UNIDADPROVEE {
            get {
                return this.uNIDADPROVEEField;
            }
            set {
                this.uNIDADPROVEEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> FECHA_COMPLETO {
            get {
                return this.fECHA_COMPLETOField;
            }
            set {
                this.fECHA_COMPLETOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> CODPAIS {
            get {
                return this.cODPAISField;
            }
            set {
                this.cODPAISField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> CODDPTO {
            get {
                return this.cODDPTOField;
            }
            set {
                this.cODDPTOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> CODPROV {
            get {
                return this.cODPROVField;
            }
            set {
                this.cODPROVField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> CODDIST {
            get {
                return this.cODDISTField;
            }
            set {
                this.cODDISTField = value;
            }
        }
        
        /// <remarks/>
        public string DIRECCION {
            get {
                return this.dIRECCIONField;
            }
            set {
                this.dIRECCIONField = value;
            }
        }
        
        /// <remarks/>
        public string OBSERV_DOC_FIN {
            get {
                return this.oBSERV_DOC_FINField;
            }
            set {
                this.oBSERV_DOC_FINField = value;
            }
        }
        
        /// <remarks/>
        public string INSTITUCION_NO_REG {
            get {
                return this.iNSTITUCION_NO_REGField;
            }
            set {
                this.iNSTITUCION_NO_REGField = value;
            }
        }
        
        /// <remarks/>
        public string ANEXOS {
            get {
                return this.aNEXOSField;
            }
            set {
                this.aNEXOSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> IDFLUJO {
            get {
                return this.iDFLUJOField;
            }
            set {
                this.iDFLUJOField = value;
            }
        }
        
        /// <remarks/>
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Persona {
        
        private System.Nullable<long> iDPERSONField;
        
        private string aPELLIDO_PATERNOField;
        
        private string aPELLIDO_MATERNOField;
        
        private string nOMBRESField;
        
        private string sEXOField;
        
        private string dNIField;
        
        private System.Nullable<long> cODPAISField;
        
        private System.Nullable<short> cODDPTOField;
        
        private System.Nullable<short> cODPROVField;
        
        private System.Nullable<short> cODDISTField;
        
        private string dIRECCIONField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> IDPERSON {
            get {
                return this.iDPERSONField;
            }
            set {
                this.iDPERSONField = value;
            }
        }
        
        /// <remarks/>
        public string APELLIDO_PATERNO {
            get {
                return this.aPELLIDO_PATERNOField;
            }
            set {
                this.aPELLIDO_PATERNOField = value;
            }
        }
        
        /// <remarks/>
        public string APELLIDO_MATERNO {
            get {
                return this.aPELLIDO_MATERNOField;
            }
            set {
                this.aPELLIDO_MATERNOField = value;
            }
        }
        
        /// <remarks/>
        public string NOMBRES {
            get {
                return this.nOMBRESField;
            }
            set {
                this.nOMBRESField = value;
            }
        }
        
        /// <remarks/>
        public string SEXO {
            get {
                return this.sEXOField;
            }
            set {
                this.sEXOField = value;
            }
        }
        
        /// <remarks/>
        public string DNI {
            get {
                return this.dNIField;
            }
            set {
                this.dNIField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> CODPAIS {
            get {
                return this.cODPAISField;
            }
            set {
                this.cODPAISField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<short> CODDPTO {
            get {
                return this.cODDPTOField;
            }
            set {
                this.cODDPTOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<short> CODPROV {
            get {
                return this.cODPROVField;
            }
            set {
                this.cODPROVField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<short> CODDIST {
            get {
                return this.cODDISTField;
            }
            set {
                this.cODDISTField = value;
            }
        }
        
        /// <remarks/>
        public string DIRECCION {
            get {
                return this.dIRECCIONField;
            }
            set {
                this.dIRECCIONField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Usuario {
        
        private string uSULOGField;
        
        private string uSUCONField;
        
        /// <remarks/>
        public string USULOG {
            get {
                return this.uSULOGField;
            }
            set {
                this.uSULOGField = value;
            }
        }
        
        /// <remarks/>
        public string USUCON {
            get {
                return this.uSUCONField;
            }
            set {
                this.uSUCONField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void BuscarProveedorCompletedEventHandler(object sender, BuscarProveedorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BuscarProveedorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BuscarProveedorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Proveedor Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Proveedor)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void BuscarPersonaCompletedEventHandler(object sender, BuscarPersonaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BuscarPersonaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BuscarPersonaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Persona Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Persona)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void AgregarProveedorCompletedEventHandler(object sender, AgregarProveedorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AgregarProveedorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AgregarProveedorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Proveedor Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Proveedor)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void AgregarPersonaCompletedEventHandler(object sender, AgregarPersonaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AgregarPersonaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AgregarPersonaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Persona Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Persona)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void AgregarHojaRutaCompletedEventHandler(object sender, AgregarHojaRutaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AgregarHojaRutaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AgregarHojaRutaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public HojaRuta Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((HojaRuta)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void ActualizarHojaRutaCompletedEventHandler(object sender, ActualizarHojaRutaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ActualizarHojaRutaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ActualizarHojaRutaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public cerrar Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((cerrar)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void ListarProcedimientoCompletedEventHandler(object sender, ListarProcedimientoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarProcedimientoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarProcedimientoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Procedimiento[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Procedimiento[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void CuentaPasosCompletedEventHandler(object sender, CuentaPasosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CuentaPasosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CuentaPasosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void AgregarAcumuladorCompletedEventHandler(object sender, AgregarAcumuladorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AgregarAcumuladorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AgregarAcumuladorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Acumulador Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Acumulador)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void Generar_ResolucionCompletedEventHandler(object sender, Generar_ResolucionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Generar_ResolucionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Generar_ResolucionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Resolucion Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Resolucion)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591